import sys

from .graph import AgentGraph
from .llms import ConversationLLM, RetrievalLLM, VerifyLLM, UpdateLLM, FillLLM, RouterLLM
from .models import ModelManager
from .parameters import InputParameters

class Agent:

    def __init__(self, model_name: str, model_preprompts: list[str], model_opening_message: str) -> None:

        self.model_manager = ModelManager(model_name)
        
        self.LLM_conversation = ConversationLLM(self.model_manager, model_preprompts[0], model_opening_message)
        self.LLM_retrieval = RetrievalLLM(self.model_manager, model_preprompts[1])
        self.LLM_verification = VerifyLLM(self.model_manager, model_preprompts[2])
        self.LLM_update = UpdateLLM(self.model_manager, model_preprompts[3])
        self.LLM_fill = FillLLM(self.model_manager, model_preprompts[4])
        self.LLM_router = RouterLLM(self.model_manager, model_preprompts[5])

        self.model_opening_message = model_opening_message

        self.graph = AgentGraph(self)

    def chat(self) -> None:

        state = {
                "user_message": "",
                "process_history": [],
                "input_parameters": InputParameters(),
                "route": None,
                "response": None,
            }

        print(f"\nAgent: {self.model_opening_message}")

        while True:
            try:
                user_input = input("\nYou: ")
                if user_input.lower() in ["exit", "quit"]: sys.exit()

                # Reset fields for new cycle
                state["process_history"] = []
                state["route"] = None

                # Update only the part of the state that changes
                state["user_message"] = user_input

                # Run the LangGraph
                state = self.graph.app.invoke(state)

                if state["route"] == "END":
                    print("\nAgent found the good input parameters.\nConversation ends here.\n")
                    sys.exit()

                # Display the response generated by the chat node
                print(f"\nAgent: {state['response']}")

            except KeyboardInterrupt:
                sys.exit()